/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import com.mycompany.trabajopractico4_laboratorio.Alumno;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucia
 */
public class Registro_alumno extends javax.swing.JInternalFrame {

    private HashSet<Alumno> alumno;

    public Registro_alumno() {
        initComponents();
    }
    
    public Registro_alumno(HashSet<Alumno> alumno) {
        this.alumno = alumno;
        initComponents();
        this.setTitle("FORMULARIO DE REGISTRO PARA ALUMNOS");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alumnos_input_legajo = new javax.swing.JTextField();
        alumnos_input_apellido = new javax.swing.JTextField();
        alumnos_input_nombre = new javax.swing.JTextField();
        btn_alumnos_guardar = new javax.swing.JButton();
        btn_alumnos_nuevo = new javax.swing.JButton();
        btb_alumnos_salir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO DE ALUMNOS");

        jLabel2.setText("LEGAJO:");

        jLabel3.setText("APELLIDO:");

        jLabel4.setText("NOMBRE:");

        btn_alumnos_guardar.setText("Guardar");
        btn_alumnos_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnos_guardarActionPerformed(evt);
            }
        });

        btn_alumnos_nuevo.setText("Nuevo");
        btn_alumnos_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnos_nuevoActionPerformed(evt);
            }
        });

        btb_alumnos_salir.setText("Salir");
        btb_alumnos_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_alumnos_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alumnos_input_legajo, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(alumnos_input_apellido)
                            .addComponent(alumnos_input_nombre))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_alumnos_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_alumnos_nuevo)
                .addGap(18, 18, 18)
                .addComponent(btb_alumnos_salir)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnos_input_legajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnos_input_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnos_input_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alumnos_guardar)
                    .addComponent(btn_alumnos_nuevo)
                    .addComponent(btb_alumnos_salir))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*GUARDAR ALUMNO NUEVO EN HASSHET*/
    private void btn_alumnos_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnos_guardarActionPerformed
        
    Alumno alu = new Alumno();
    
    alu.setNombre(alumnos_input_nombre.getText());
    alu.setApellido(alumnos_input_apellido.getText());
    alu.setNroLegajo(Integer.parseInt(alumnos_input_legajo.getText()));
    
    if (alumno.add(alu)){
    JOptionPane.showMessageDialog(this, "El alumno: " + alu.getNombre() + " " + alu.getApellido() + " Se ha añadido correctamente.");
    
    } else {
        JOptionPane.showMessageDialog(this, "El alumno ya existe.");
    }
     
    limpiarFormulario();
   
    mostrarAlumnos();
    }//GEN-LAST:event_btn_alumnos_guardarActionPerformed

   public void mostrarAlumnos() {
    // Suponiendo que 'alumno' es el HashSet de tipo Alumno
    for (Alumno alu : alumno) {
        System.out.println("Nombre: " + alu.getNombre() + ", Apellido: " + alu.getApellido() + ", Legajo: " + alu.getNroLegajo());
    }
}
    
    private void btn_alumnos_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnos_nuevoActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btn_alumnos_nuevoActionPerformed

    private void btb_alumnos_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_alumnos_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btb_alumnos_salirActionPerformed

    private void limpiarFormulario(){
    alumnos_input_nombre.setText("");
    alumnos_input_apellido.setText("");
    alumnos_input_legajo.setText("");
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alumnos_input_apellido;
    private javax.swing.JTextField alumnos_input_legajo;
    private javax.swing.JTextField alumnos_input_nombre;
    private javax.swing.JButton btb_alumnos_salir;
    private javax.swing.JButton btn_alumnos_guardar;
    private javax.swing.JButton btn_alumnos_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
